### PR TITLE
Sync headers with PulseAudio 12.2

### PR DESCRIPTION
**Pull request by Vaelatern**
I hope I did this right, I tried to use your new Makefile target.

### CODE REVIEW

**Comment by Vaelatern** [comment]
I suspect I got it wrong because I used HEAD, not a tag. One moment...

**Comment by Vaelatern** [comment]
Updated.

**Comment by Vaelatern** [comment]
I don't understand if this is actually necessary, or if I just must relink against pulseaudio's library.

**Comment by t6** [comment]
Thanks.

> I don't understand if this is actually necessary, or if I just must relink against pulseaudio's library.

Given the changes I think just relinking is fine.  

I'll merge it, but I don't think a new release is needed as there don't seem to be any ABI changes.

**Pull request merged**
